import mainHeaderBackground from "./components/main-header-background";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >

        <mainHeaderBackground />
        {children}
      </body>
    </html>
  );
}
